// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OTTimetableApp.Data;

#nullable disable

namespace OTTimetableApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260303070206_AddEmployeeBaseGroup_Nullable")]
    partial class AddEmployeeBaseGroup_Nullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("OTTimetableApp.Data.Models.Calendar", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("InitEveningGroupId")
                        .HasColumnType("int");

                    b.Property<int>("InitMorningGroupId")
                        .HasColumnType("int");

                    b.Property<int>("InitNightGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Name")
                        .IsUnique();

                    b.ToTable("Calendars");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.CalendarDay", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarId")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("EveningGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsPublicHoliday")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MorningGroupId")
                        .HasColumnType("int");

                    b.Property<int>("NightGroupId")
                        .HasColumnType("int");

                    b.Property<int>("OffGroupId")
                        .HasColumnType("int");

                    b.Property<string>("PublicHolidayName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CalendarId", "Date")
                        .IsUnique();

                    b.ToTable("CalendarDays");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BaseGroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("BaseGroupId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("SlotCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("GroupId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.ShiftAssignment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CalendarDayId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("CalendarDayId", "ShiftType")
                        .IsUnique();

                    b.ToTable("ShiftAssignments");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.ShiftSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ActualEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("FillType")
                        .HasColumnType("int");

                    b.Property<int?>("PlannedEmployeeId")
                        .HasColumnType("int");

                    b.Property<int?>("ReplacedEmployeeId")
                        .HasColumnType("int");

                    b.Property<int>("ShiftAssignmentId")
                        .HasColumnType("int");

                    b.Property<int>("SlotIndex")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ActualEmployeeId");

                    b.HasIndex("PlannedEmployeeId");

                    b.HasIndex("ReplacedEmployeeId");

                    b.HasIndex("ShiftAssignmentId", "SlotIndex")
                        .IsUnique();

                    b.ToTable("ShiftSlots");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.CalendarDay", b =>
                {
                    b.HasOne("OTTimetableApp.Data.Models.Calendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.Employee", b =>
                {
                    b.HasOne("OTTimetableApp.Data.Models.Group", "BaseGroup")
                        .WithMany()
                        .HasForeignKey("BaseGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("BaseGroup");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.GroupMember", b =>
                {
                    b.HasOne("OTTimetableApp.Data.Models.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OTTimetableApp.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.ShiftAssignment", b =>
                {
                    b.HasOne("OTTimetableApp.Data.Models.CalendarDay", "CalendarDay")
                        .WithMany()
                        .HasForeignKey("CalendarDayId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("OTTimetableApp.Data.Models.Group", "Group")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CalendarDay");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("OTTimetableApp.Data.Models.ShiftSlot", b =>
                {
                    b.HasOne("OTTimetableApp.Data.Models.Employee", "ActualEmployee")
                        .WithMany()
                        .HasForeignKey("ActualEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OTTimetableApp.Data.Models.Employee", "PlannedEmployee")
                        .WithMany()
                        .HasForeignKey("PlannedEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OTTimetableApp.Data.Models.Employee", "ReplacedEmployee")
                        .WithMany()
                        .HasForeignKey("ReplacedEmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("OTTimetableApp.Data.Models.ShiftAssignment", "ShiftAssignment")
                        .WithMany()
                        .HasForeignKey("ShiftAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ActualEmployee");

                    b.Navigation("PlannedEmployee");

                    b.Navigation("ReplacedEmployee");

                    b.Navigation("ShiftAssignment");
                });
#pragma warning restore 612, 618
        }
    }
}
